// Builds the Notre Ligue share image (1200 by 630 PNG) with Playwright's
// Chromium, from the design system: the wordmark (Archivo wide 800,
// uppercase, after its yellow square), the homepage's French H1 under it,
// a near-black #16181d background and the yellow #ffd23f accent. The font is
// the Archivo the Worker already serves (src/fonts_archivo.js).
// Writes assets/share/notre-ligue-share.png and src/share_image.js (the
// PNG as base64, served at /share/notre-ligue.png).
//   node scripts/build_share_image.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { chromium } from 'playwright';
import { ARCHIVO_WOFF2 } from '../src/fonts_archivo.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const H1 = 'Tes joueurs répondent sans compte et sans application.';
const face = name => `@font-face{font-family:'Archivo';font-weight:400 800;font-stretch:62% 125%;src:url(data:font/woff2;base64,${ARCHIVO_WOFF2[name]}) format('woff2');}`;
const html = `<!doctype html><html><head><meta charset="utf-8"><style>
${face('archivo-latin.woff2')}${face('archivo-latin-ext.woff2')}
html,body{margin:0;width:1200px;height:630px;background:#16181d;}
body{display:flex;flex-direction:column;justify-content:center;padding:0 96px;box-sizing:border-box;font-family:'Archivo',sans-serif;color:#f4f4f2;}
.mark{display:flex;align-items:center;gap:22px;font-weight:800;font-stretch:118%;font-size:44px;letter-spacing:.04em;text-transform:uppercase;line-height:1;}
.mark i{display:block;width:30px;height:30px;background:#ffd23f;border-radius:3px;}
h1{margin:56px 0 0;font-weight:800;font-stretch:118%;font-size:68px;line-height:76px;letter-spacing:-.01em;max-width:960px;text-wrap:balance;}
.bar{position:absolute;left:0;bottom:0;width:1200px;height:14px;background:#ffd23f;}
</style></head><body><div class="mark"><i></i>Notre Ligue</div><h1>${H1}</h1><div class="bar"></div></body></html>`;

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 1 });
await page.setContent(html);
await page.evaluate(() => document.fonts.ready);
const png = await page.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 1200, height: 630 } });
await browser.close();

mkdirSync(join(root, 'assets', 'share'), { recursive: true });
writeFileSync(join(root, 'assets', 'share', 'notre-ligue-share.png'), png);
writeFileSync(join(root, 'src', 'share_image.js'), `// Generated by scripts/build_share_image.mjs: the Notre Ligue share image
// (1200 by 630 PNG, assets/share/notre-ligue-share.png), served at
// /share/notre-ligue.png on the Notre Ligue product.
export const SHARE_IMAGE_PATH = '/share/notre-ligue.png';
export const SHARE_IMAGE_WIDTH = 1200;
export const SHARE_IMAGE_HEIGHT = 630;
export const SHARE_IMAGE_PNG_BASE64 = '${png.toString('base64')}';
`);
console.log('share image', png.length, 'bytes');
