// Builds the Notre Ligue share images (1200 by 630 PNG), one per language,
// with Playwright's Chromium, from the design system: the wordmark (Archivo
// wide 800, uppercase, after its yellow square), the homepage's H1 under it,
// a near-black #16181d background and the yellow #ffd23f accent. The font is
// the Archivo the Worker already serves (src/fonts_archivo.js).
// Writes assets/share/notre-ligue-share.png (French),
// assets/share/notre-ligue-share-en.png (English) and src/share_image.js
// (both PNGs as base64, served at /share/notre-ligue.png and
// /share/notre-ligue-en.png: each language has its own URL, because
// Facebook caches a preview by image URL).
//   node scripts/build_share_image.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { chromium } from 'playwright';
import { ARCHIVO_WOFF2 } from '../src/fonts_archivo.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const IMAGES = {
  fr: { h1: 'Tes joueurs répondent sans compte et sans application.', file: 'notre-ligue-share.png', path: '/share/notre-ligue.png' },
  en: { h1: 'Your players answer without an account or an app.', file: 'notre-ligue-share-en.png', path: '/share/notre-ligue-en.png' }
};
const face = name => `@font-face{font-family:'Archivo';font-weight:400 800;font-stretch:62% 125%;src:url(data:font/woff2;base64,${ARCHIVO_WOFF2[name]}) format('woff2');}`;
const html = (lang, h1) => `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><style>
${face('archivo-latin.woff2')}${face('archivo-latin-ext.woff2')}
html,body{margin:0;width:1200px;height:630px;background:#16181d;}
body{display:flex;flex-direction:column;justify-content:center;padding:0 96px;box-sizing:border-box;font-family:'Archivo',sans-serif;color:#f4f4f2;}
.mark{display:flex;align-items:center;gap:22px;font-weight:800;font-stretch:118%;font-size:44px;letter-spacing:.04em;text-transform:uppercase;line-height:1;}
.mark i{display:block;width:30px;height:30px;background:#ffd23f;border-radius:3px;}
h1{margin:56px 0 0;font-weight:800;font-stretch:118%;font-size:68px;line-height:76px;letter-spacing:-.01em;max-width:960px;text-wrap:balance;}
.bar{position:absolute;left:0;bottom:0;width:1200px;height:14px;background:#ffd23f;}
</style></head><body><div class="mark"><i></i>Notre Ligue</div><h1>${h1}</h1><div class="bar"></div></body></html>`;

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 1 });
const png = {};
for (const [lang, img] of Object.entries(IMAGES)) {
  await page.setContent(html(lang, img.h1));
  await page.evaluate(() => document.fonts.ready);
  png[lang] = await page.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 1200, height: 630 } });
}
await browser.close();

mkdirSync(join(root, 'assets', 'share'), { recursive: true });
for (const [lang, img] of Object.entries(IMAGES)) writeFileSync(join(root, 'assets', 'share', img.file), png[lang]);
writeFileSync(join(root, 'src', 'share_image.js'), `// Generated by scripts/build_share_image.mjs: the Notre Ligue share images
// (1200 by 630 PNG, assets/share/), one per language, each at its own URL,
// on the Notre Ligue product.
export const SHARE_IMAGE_WIDTH = 1200;
export const SHARE_IMAGE_HEIGHT = 630;
export const SHARE_IMAGES = {
  fr: { path: '${IMAGES.fr.path}', base64: '${png.fr.toString('base64')}' },
  en: { path: '${IMAGES.en.path}', base64: '${png.en.toString('base64')}' }
};
// The French image, under the names it had before the English one.
export const SHARE_IMAGE_PATH = SHARE_IMAGES.fr.path;
export const SHARE_IMAGE_PNG_BASE64 = SHARE_IMAGES.fr.base64;
`);
for (const lang of Object.keys(IMAGES)) console.log('share image', lang, png[lang].length, 'bytes');
