// Builds src/fonts_archivo.js from the Archivo woff2 files (the latin and
// latin-ext subsets of Google Fonts' variable Archivo, weights 400 to 800,
// widths 62 to 125 %; SIL Open Font License 1.1, which allows this). Notre
// Ligue's pages load the font from this Worker (/fonts/...), so a visit
// sends no request to Google.
//   node scripts/build_fonts.mjs <dir with archivo-latin.woff2 and archivo-latin-ext.woff2>
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = process.argv[2];
if (!dir) throw new Error('usage: node scripts/build_fonts.mjs <dir>');
const b64 = name => readFileSync(join(dir, name)).toString('base64');
writeFileSync(join(root, 'src', 'fonts_archivo.js'), `// Generated by scripts/build_fonts.mjs: Archivo (SIL Open Font License
// 1.1, https://openfontlicense.org), the latin and latin-ext subsets,
// served by the Worker at /fonts/<name>.woff2 (index.js fontRoute).
export const ARCHIVO_WOFF2 = {
  'archivo-latin.woff2': '${b64('archivo-latin.woff2')}',
  'archivo-latin-ext.woff2': '${b64('archivo-latin-ext.woff2')}'
};
`);
console.log('src/fonts_archivo.js written');
