// Builds src/legal_text.js from legal/privacy.md and legal/terms.md, the
// texts Roberto exports from his drafts. Run after changing either file:
//   node scripts/build_legal.mjs
// The "Statut / Status" section is a private review note and is left out;
// everything else is kept as written. test/rendered/legal_text_sync.spec.mjs
// fails when src/legal_text.js no longer matches the two files.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// { title, fr, en }: the H1, then the French and the English sections'
// own markdown (without their "## Version française" / "## English
// version" headings).
export function splitLegal(md) {
  const text = md.replace(/\r\n?/g, '\n');
  const title = (text.match(/^# (.+)$/m) || [, ''])[1].trim();
  const fr = text.indexOf('\n## Version française\n');
  const en = text.indexOf('\n## English version\n');
  if (fr === -1 || en === -1 || en < fr) throw new Error('legal text: "## Version française" then "## English version" expected');
  const after = i => text.indexOf('\n', i + 1) + 1;
  return {
    title,
    fr: text.slice(after(fr), en).trim(),
    en: text.slice(after(en)).trim()
  };
}

export function buildLegalModule() {
  const out = {};
  for (const kind of ['privacy', 'terms']) out[kind] = splitLegal(readFileSync(join(root, 'legal', `${kind}.md`), 'utf8'));
  return `// Generated by scripts/build_legal.mjs from legal/privacy.md and
// legal/terms.md. Do not edit by hand: change the .md file and run
//   node scripts/build_legal.mjs
export const LEGAL_TEXT = ${JSON.stringify(out, null, 2)};
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(join(root, 'src', 'legal_text.js'), buildLegalModule());
  console.log('src/legal_text.js written');
}
