// Schema-drift guard, runtime half. Built after the Sept 24 production
// incident: 22 migrations had been applied to the demo database but
// never to production, so a deploy shipped code that unconditionally
// wrote to outbox.league_id -- a column production's schema didn't
// have -- and broke SMBHL's live admin. Nothing checked this before
// that deploy went out. This is that check, running automatically in
// whichever environment the Worker is actually deployed to.
//
// HOW IT WORKS: SCHEMA_MANIFEST (schema_manifest.js, generated by
// scripts/generate_schema_manifest.js from the real migrate-*.sql
// files -- see that script's own header) lists every table/column the
// migration chain has ever added. On the first request handled by a
// given isolate, this queries env.DB directly via PRAGMA table_info --
// the database's own live, authoritative schema, not a trust-based
// "we believe we already ran this" log -- and compares. The result is
// memoized for the rest of that isolate's lifetime (a schema cannot
// change without a new deploy, so a genuine determination made once
// stays valid).
//
// FALSE-POSITIVE SAFETY (this guard must never become its own outage):
//   - It only asserts column/table EXISTENCE. No migration in this
//     repo's history has ever dropped a column, so this can only ever
//     be a true positive (really behind) or a true negative (really
//     caught up) -- there's no scenario where a real, unmodified
//     manifest wrongly flags a healthy database.
//   - If the check itself cannot run (D1 unreachable, a transient
//     error) that is NOT treated as drift -- it fails OPEN (serves
//     normally) rather than turning an infrastructure hiccup into a
//     hard outage. Only a successfully-completed check that finds a
//     genuine gap blocks anything. A failed check is also never
//     cached, so the next request naturally retries it.
import { SCHEMA_MANIFEST } from './schema_manifest.js';

let cachedResult = null; // only ever holds a successful, real determination

async function runCheck(env) {
  const tables = Object.keys(SCHEMA_MANIFEST);
  // Table names here come exclusively from the generated manifest
  // (derived from this repo's own committed migration files), never
  // from request input -- safe to interpolate even though PRAGMA
  // doesn't support bound-parameter identifiers in SQLite/D1.
  const perTable = await Promise.all(tables.map(async table => {
    const rows = (await env.DB.prepare(`PRAGMA table_info(${table})`).all()).results || [];
    return { table, columns: new Set(rows.map(r => r.name)) };
  }));

  const missing = [];
  for (const { table, columns } of perTable) {
    if (columns.size === 0) {
      missing.push({ table, column: null });
      continue;
    }
    for (const column of SCHEMA_MANIFEST[table]) {
      if (!columns.has(column)) missing.push({ table, column });
    }
  }
  return missing.length === 0 ? { ok: true } : { ok: false, missing };
}

// Returns { ok: true } | { ok: false, missing: [{table, column}] } |
// { ok: true, checkFailed: true, error }. Safe to call on every
// request -- only the very first call per isolate actually queries D1;
// every call after that (whether ok or genuinely not-ok) returns the
// same cached, real determination instantly.
export async function checkSchemaOnce(env) {
  if (cachedResult) return cachedResult;
  try {
    const result = await runCheck(env);
    cachedResult = result; // only cache a real, completed determination
    return result;
  } catch (err) {
    return { ok: true, checkFailed: true, error: String((err && err.message) || err) };
  }
}

// One specific, human-readable line per missing thing -- "fail loudly
// and specifically, naming what's missing," not a generic 500.
export function formatSchemaDriftMessage(missing) {
  const lines = missing.map(({ table, column }) =>
    column === null
      ? `table "${table}" does not exist`
      : `table "${table}" has no column named "${column}"`
  );
  return `Schema drift detected -- this database is missing something the deployed code expects:\n${lines.join('\n')}\nApply the pending migration(s) (see migrate-*.sql in the repo root and DEPLOY.md) before this deployment can serve traffic correctly.`;
}

// Test-only: clears the per-isolate memo so a test can exercise both a
// fresh "not yet checked" state and a forced re-check against a
// different (e.g. deliberately drifted) env.DB.
export function _resetSchemaGuardCacheForTests() {
  cachedResult = null;
}
