// Schema-drift guard, runtime half. Built after the Sept 24 production
// incident: 22 migrations had been applied to the demo database but
// never to production, so a deploy shipped code that unconditionally
// wrote to outbox.league_id -- a column production's schema didn't
// have -- and broke SMBHL's live admin. Nothing checked this before
// that deploy went out. This is that check, running automatically in
// whichever environment the Worker is actually deployed to.
//
// HOW IT WORKS: SCHEMA_MANIFEST (schema_manifest.js, generated by
// scripts/generate_schema_manifest.js from the real migrate-*.sql
// files -- see that script's own header) lists every table/column the
// migration chain has ever added. On the first request handled by a
// given isolate, this queries env.DB directly via PRAGMA table_info --
// the database's own live, authoritative schema, not a trust-based
// "we believe we already ran this" log -- and compares. A clean result
// is memoized for the rest of that isolate's lifetime (the deployed code
// can't change under it); a result that finds the database behind is
// not, so the migration being applied clears it on the next request.
// Scheduled passes run the same check first (checkSchemaForPass).
//
// FALSE-POSITIVE SAFETY (this guard must never become its own outage):
//   - It only asserts column/table EXISTENCE. No migration in this
//     repo's history has ever dropped a column, so this can only ever
//     be a true positive (really behind) or a true negative (really
//     caught up) -- there's no scenario where a real, unmodified
//     manifest wrongly flags a healthy database.
//   - If the check itself cannot run (D1 unreachable, a transient
//     error) that is NOT treated as drift -- it fails OPEN (serves
//     normally) rather than turning an infrastructure hiccup into a
//     hard outage. Only a successfully-completed check that finds a
//     genuine gap blocks anything. A failed check is also never
//     cached, so the next request naturally retries it.
import { SCHEMA_MANIFEST } from './schema_manifest.js';

let cachedResult = null; // only ever holds a successful, real determination

async function runCheck(env) {
  const tables = Object.keys(SCHEMA_MANIFEST);
  // Table names here come exclusively from the generated manifest
  // (derived from this repo's own committed migration files), never
  // from request input -- safe to interpolate even though PRAGMA
  // doesn't support bound-parameter identifiers in SQLite/D1.
  const perTable = await Promise.all(tables.map(async table => {
    const rows = (await env.DB.prepare(`PRAGMA table_info(${table})`).all()).results || [];
    return { table, columns: new Set(rows.map(r => r.name)) };
  }));

  const missing = [];
  for (const { table, columns } of perTable) {
    if (columns.size === 0) {
      missing.push({ table, column: null });
      continue;
    }
    for (const column of SCHEMA_MANIFEST[table]) {
      if (!columns.has(column)) missing.push({ table, column });
    }
  }
  return missing.length === 0 ? { ok: true } : { ok: false, missing };
}

// Returns { ok: true } | { ok: false, missing: [{table, column}] } |
// { ok: true, checkFailed: true, error }. Safe to call on every
// request -- only the very first call per isolate actually queries D1;
// every call after that (whether ok or genuinely not-ok) returns the
// same cached, real determination instantly.
export async function checkSchemaOnce(env) {
  if (cachedResult) return cachedResult;
  try {
    const result = await runCheck(env);
    // Only a clean result is kept: a database found behind is checked
    // again on the next request, so applying the migration clears the 503
    // without a redeploy (an isolate that had kept "behind" stayed down
    // until it was recycled). The site is down meanwhile anyway, so the
    // repeated PRAGMAs cost nothing that matters.
    if (result.ok) cachedResult = result;
    return result;
  } catch (err) {
    return { ok: true, checkFailed: true, error: String((err && err.message) || err) };
  }
}

// Before a scheduled pass (runCronPass). Requests were guarded; the cron
// was not, so code deployed ahead of its migrations could send an email
// and then fail to record it -- and send it again next pass. Same check,
// with three differences:
//   - a clean result is remembered per DEPLOYED VERSION
//     (env.CF_VERSION_METADATA.id, wrangler.jsonc version_metadata) in
//     the settings table (a migrate-002 table, there in any database this
//     code can meet), so each fresh isolate's pass reads one row instead
//     of a PRAGMA per table: only the first pass after a deploy pays;
//   - a database found behind is never remembered -- each pass checks
//     again, so applying the migration (no redeploy) lets the next pass
//     run;
//   - as for requests, a check that cannot run fails open: the pass runs.
// Returns { ok, missing?, checkFailed?, error?, source: 'isolate' |
// 'version' | 'checked' }.
export const SCHEMA_OK_PREFIX = 'schema:ok:';
export async function checkSchemaForPass(env) {
  if (cachedResult && cachedResult.ok) return { ok: true, source: 'isolate' };
  const version = (env.CF_VERSION_METADATA && env.CF_VERSION_METADATA.id) || null;
  const key = version ? `${SCHEMA_OK_PREFIX}${version}` : null;
  if (key) {
    try {
      if (await env.DB.prepare('SELECT 1 FROM settings WHERE key = ?').bind(key).first()) {
        cachedResult = { ok: true };
        return { ok: true, source: 'version' };
      }
    } catch (_) { /* fall through to the real check */ }
  }
  let result;
  try {
    result = await runCheck(env);
  } catch (err) {
    return { ok: true, checkFailed: true, error: String((err && err.message) || err), source: 'checked' };
  }
  if (result.ok) {
    cachedResult = result;
    if (key) {
      try {
        await env.DB.prepare('INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO NOTHING')
          .bind(key, new Date().toISOString()).run();
      } catch (_) { /* remembering is an optimisation only */ }
    }
  }
  return { ...result, source: 'checked' };
}

// One specific, human-readable line per missing thing -- "fail loudly
// and specifically, naming what's missing," not a generic 500.
export function formatSchemaDriftMessage(missing) {
  const lines = missing.map(({ table, column }) =>
    column === null
      ? `table "${table}" does not exist`
      : `table "${table}" has no column named "${column}"`
  );
  return `Schema drift detected -- this database is missing something the deployed code expects:\n${lines.join('\n')}\nApply the pending migration(s) (see migrate-*.sql in the repo root and DEPLOY.md) before this deployment can serve traffic correctly.`;
}

// Test-only: clears the per-isolate memo so a test can exercise both a
// fresh "not yet checked" state and a forced re-check against a
// different (e.g. deliberately drifted) env.DB.
export function _resetSchemaGuardCacheForTests() {
  cachedResult = null;
}
